version: "3"
services:
  cryptogalaxy0:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy0
    restart: always
    volumes:
      - /cdnf/cryptologger0.log:/cryptogalaxy/cryptologger.log
      - ./config0.json:/cryptogalaxy/config.json
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.3
  cryptogalaxy1:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy1
    restart: always
    volumes:
      - /cdnf/cryptologger1.log:/cryptogalaxy/cryptologger.log
      - ./config1.json:/cryptogalaxy/config.json
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.4
  cryptogalaxy2:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy2
    restart: always
    volumes:
      - /cdnf/cryptologger2.log:/cryptogalaxy/cryptologger.log
      - ./config2.json:/cryptogalaxy/config.json
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.5
  cryptogalaxy3:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy3
    restart: always
    volumes:
      - /cdnf/cryptologger3.log:/cryptogalaxy/cryptologger.log
      - ./config3.json:/cryptogalaxy/config.json
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.6
  cryptogalaxy4:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy4
    restart: always
    volumes:
      - /cdnf/cryptologger4.log:/cryptogalaxy/cryptologger.log
      - ./config4.json:/cryptogalaxy/config.json
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.7
  cryptogalaxy5:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy5
    restart: always
    volumes:
      - /cdnf/cryptologger5.log:/cryptogalaxy/cryptologger.log
      - ./config5.json:/cryptogalaxy/config.json
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.8
  cryptogalaxy6:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy6
    restart: always
    volumes:
      - /cdnf/cryptologger6.log:/cryptogalaxy/cryptologger.log
      - ./config6.json:/cryptogalaxy/config.json
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.9
  cryptogalaxy7:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy7
    restart: always
    volumes:
      - /cdnf/cryptologger7.log:/cryptogalaxy/cryptologger.log
      - ./config7.json:/cryptogalaxy/config.json
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.10
  cryptogalaxy8:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy8
    restart: always
    volumes:
      - /cdnf/cryptologger8.log:/cryptogalaxy/cryptologger.log
      - ./config8.json:/cryptogalaxy/config.json
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.11
  cryptogalaxy9:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy9
    restart: always
    volumes:
      - /cdnf/cryptologger9.log:/cryptogalaxy/cryptologger.log
      - ./config9.json:/cryptogalaxy/config.json
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.12
  db:
    image: yandex/clickhouse-server
    restart: always
    container_name: db
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /cdnf/db/log:/var/log/clickhouse-server
      - /cdnf/db/data:/var/lib/clickhouse
      - /cdnc:/home/cold_storage
      - ./settings/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./settings/clickhouse/config.xml:/etc/clickhouse-server/config.xml
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    networks:
      intranet:
        ipv4_address: 172.23.0.2
  logparser:
    hostname: logparser
    build:
      context: ./logParser
      dockerfile: ./Dockerfile
    container_name: logparser
    env_file: ./settings/logparser.env
    ports:
      - "8100:4000"
    volumes:
      - ./logParser:/home/app
      - /home/app/node_modules
      - /home/app/build
      - /cdnf/cryptologger0.log:/home/app/cryptologger0.log
      - /cdnf/cryptologger1.log:/home/app/cryptologger1.log
      - /cdnf/cryptologger2.log:/home/app/cryptologger2.log
      - /cdnf/cryptologger3.log:/home/app/cryptologger3.log
      - /cdnf/cryptologger4.log:/home/app/cryptologger4.log
      - /cdnf/cryptologger5.log:/home/app/cryptologger5.log
      - /cdnf/cryptologger6.log:/home/app/cryptologger6.log
      - /cdnf/cryptologger7.log:/home/app/cryptologger7.log
      - /cdnf/cryptologger8.log:/home/app/cryptologger8.log
      - /cdnf/cryptologger9.log:/home/app/cryptologger9.log
      - ./config0.json:/home/app/configs/config0.json
      - ./config1.json:/home/app/configs/config1.json
      - ./config2.json:/home/app/configs/config2.json
      - ./config3.json:/home/app/configs/config3.json
      - ./config4.json:/home/app/configs/config4.json
      - ./config5.json:/home/app/configs/config5.json
      - ./config6.json:/home/app/configs/config6.json
      - ./config7.json:/home/app/configs/config7.json
      - ./config8.json:/home/app/configs/config8.json
      - ./config9.json:/home/app/configs/config9.json
    working_dir: /home/app
    restart: always
    networks:
      intranet:
        ipv4_address: 172.23.0.100

networks:
  intranet:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
