version: "3"
services:
  cryptologger:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptologger
    restart: on-failure
    volumes:
      - /cdnf/cryptologger.log:/cryptologger/cryptologger.log
    depends_on:
      - db
  db:
    image: yandex/clickhouse-server
    restart: always
    container_name: db
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /cdnf/db/log:/var/log/clickhouse-server
      - /cdnf/db/data:/var/lib/clickhouse
      - ./settings/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./settings/clickhouse/config.xml:/etc/clickhouse-server/config.xml
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
      - "9005:9005"
