version: "3"
services:
  cryptogalaxy:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cryptogalaxy
    restart: always
    volumes:
      - /cdnf/cryptologger.log:/cryptogalaxy/cryptologger.log
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 172.23.0.3
  db:
    image: yandex/clickhouse-server
    restart: always
    container_name: db
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /cdnf/db/log:/var/log/clickhouse-server
      - /cdnf/db/data:/var/lib/clickhouse
      - ./settings/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./settings/clickhouse/config.xml:/etc/clickhouse-server/config.xml
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    networks:
      intranet:
        ipv4_address: 172.23.0.2

networks:
  intranet:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
